export const AllPicks = {
  UPDATE_CUSTOMER_PICKS_TOTALS: "UPDATE_CUSTOMER_PICKS_TOTALS",
  UPDATE_SHIPMENT_PICKS_TOTALS: "UPDATE_SHIPMENT_PICKS_TOTALS",
  UPDATE_CUSTOMER_PICKS_IN_PROGRESS_TOTALS: "UPDATE_CUSTOMER_PICKS_IN_PROGRESS_TOTALS",
  UPDATE_SHIPMENT_PICKS_IN_PROGRESS_TOTALS: "UPDATE_SHIPMENT_PICKS_IN_PROGRESS_TOTALS",
}