export const AllShipments = {
  UPDATE_SHIPMENTS_TO_PACK_TOTALS: "UPDATE_SHIPMENTS_TO_PACK_TOTALS",
  UPDATE_PACKING_IN_PROGRESS_TOTALS: "UPDATE_PACKING_IN_PROGRESS_TOTALS",
  UPDATE_SHIPMENTS_TO_SHIP_TOTALS: "UPDATE_SHIPMENTS_TO_SHIP_TOTALS",
}