export const App = {
  UPDATE_APP_ERROR: "UPDATE_APP_ERROR",
  UPDATE_IS_LOADING: "UPDATE_IS_LOADING",
  UPDATE_CURRENT_SCREEN: "UPDATE_CURRENT_SCREEN",
  UPDATE_AUTH_TIME: "UPDATE_AUTH_TIME",
  UPDATE_USER_AUTHENTICATION_STATE: "UPDATE_USER_AUTHENTICATION_STATE",
  CHANGE_PAGE_LIMIT: "CHANGE_PAGE_LIMIT",
  GOTO_SEARCH_ADVANCE: "GOTO_SEARCH_ADVANCE",
  ADD_TO_LEFT_MENU: "ADD_TO_LEFT_MENU",
  LAST_ACTIVE_LIST: "LAST_ACTIVE_LIST",
  REMOVE_FROM_LEFT_TAB: "REMOVE_FROM_LEFT_TAB",
  UPDATE_ADVANCE_MENU_URL:"UPDATE_ADVANCE_MENU_URL",
  UPDATE_RETURN_SEARCH_MENU_URL: "UPDATE_RETURN_SEARCH_MENU_URL"
}