export const ShipmentsList = {
  UPDATE_SHIPMENTS_LIST: "UPDATE_SHIPMENTS_LIST",
  UPDATE_SHIPMENTS_LIST_FOR_CSV:"UPDATE_SHIPMENTS_LIST_FOR_CSV",
  RESET_SHIPMENT_LIST_STATE: "RESET_SHIPMENT_LIST_STATE",
  PDF_OWNER_DETAIL: "PDF_OWNER_DETAIL",
  REUTRN_ORDER_LIST: "REUTRN_ORDER_LIST"
}